# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preinsc', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Recibida', 'Recibida'), ('Confirmada', 'Confirmada'), ('Respondida', 'Respondida'), ('Derivada', 'Derivada')], default='Recibida', max_length=10)),
                ('fecha_recibido', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmado', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=20)),
                ('area', models.ForeignKey(default='Administracion', on_delete=django.db.models.deletion.CASCADE, to='mesaentrada.Area')),
                ('idficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preinsc.Ficha')),
            ],
        ),
    ]
