# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesaentrada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='personal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mesaentrada.PesonalColegio'),
        ),
    ]
