# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesaentrada', '0002_nota_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='personal',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='mesaentrada.PesonalColegio'),
        ),
    ]
